INSERT INTO `image`(`type`, original_name, extension, hash, path, deletable, deleted) VALUES
  ('image_permanent', 'no-image-100x75.png', 'png', 'HjE45Gd20170822093499SPf4AcC', '/no-image-100x75.png', 0, 0),

  ('image_permanent', 'active_atrais.png', 'png', 'Hactive_atraisC', '/badge/active_atrais.png', 0, 0),
  ('image_permanent', 'active_botanics.png', 'png', 'Hactive_botanicsC', '/badge/active_botanics.png', 0, 0),
  ('image_permanent', 'active_braliba.png', 'png', 'Hactive_bralibaC', '/badge/active_braliba.png', 0, 0),
  ('image_permanent', 'active_cirulis.png', 'png', 'Hactive_cirulisC', '/badge/active_cirulis.png', 0, 0),
  ('image_permanent', 'active_draudzigais.png', 'png', 'Hactive_draudzigaisC', '/badge/active_draudzigais.png', 0, 0),
  ('image_permanent', 'active_eksperts.png', 'png', 'Hactive_ekspertsC', '/badge/active_eksperts.png', 0, 0),
  ('image_permanent', 'active_geologs.png', 'png', 'Hactive_geologsC', '/badge/active_geologs.png', 0, 0),
  ('image_permanent', 'active_gudrinieks.png', 'png', 'Hactive_gudrinieksC', '/badge/active_gudrinieks.png', 0, 0),
  ('image_permanent', 'active_jauninas.png', 'png', 'Hactive_jauninasC', '/badge/active_jauninas.png', 0, 0),
  ('image_permanent', 'active_kaltietis.png', 'png', 'Hactive_kaltietisC', '/badge/active_kaltietis.png', 0, 0),
  ('image_permanent', 'active_merktiecigas.png', 'png', 'Hactive_merktiecigasC', '/badge/active_merktiecigas.png', 0, 0),
  ('image_permanent', 'active_piecenieks.png', 'png', 'Hactive_piecenieksC', '/badge/active_piecenieks.png', 0, 0),
  ('image_permanent', 'active_professors.png', 'png', 'Hactive_professorsC', '/badge/active_professors.png', 0, 0),
  ('image_permanent', 'active_puce.png', 'png', 'Hactive_puceC', '/badge/active_puce.png', 0, 0),
  ('image_permanent', 'active_talredzigais.png', 'png', 'Hactive_talredzigaisC', '/badge/active_talredzigais.png', 0, 0),
  ('image_permanent', 'active_udensvirs.png', 'png', 'Hactive_udensvirsC', '/badge/active_udensvirs.png', 0, 0),
  ('image_permanent', 'active_zintkarais.png', 'png', 'Hactive_zintkaraisC', '/badge/active_zintkarais.png', 0, 0),
  ('image_permanent', 'active_zoologs.png', 'png', 'Hactive_zoologsC', '/badge/active_zoologs.png', 0, 0),

  ('image_permanent', 'inactive_atrais.png', 'png', 'Hinactive_atraisC', '/badge/inactive_atrais.png', 0, 0),
  ('image_permanent', 'inactive_botanics.png', 'png', 'Hinactive_botanicsC', '/badge/inactive_botanics.png', 0, 0),
  ('image_permanent', 'inactive_braliba.png', 'png', 'Hinactive_bralibaC', '/badge/inactive_braliba.png', 0, 0),
  ('image_permanent', 'inactive_cirulis.png', 'png', 'Hinactive_cirulisC', '/badge/inactive_cirulis.png', 0, 0),
  ('image_permanent', 'inactive_draudzigais.png', 'png', 'Hinactive_draudzigaisC', '/badge/inactive_draudzigais.png', 0, 0),
  ('image_permanent', 'inactive_eksperts.png', 'png', 'Hinactive_ekspertsC', '/badge/inactive_eksperts.png', 0, 0),
  ('image_permanent', 'inactive_geologs.png', 'png', 'Hinactive_geologsC', '/badge/inactive_geologs.png', 0, 0),
  ('image_permanent', 'inactive_gudrinieks.png', 'png', 'Hinactive_gudrinieksC', '/badge/inactive_gudrinieks.png', 0, 0),
  ('image_permanent', 'inactive_jauninas.png', 'png', 'Hinactive_jauninasC', '/badge/inactive_jauninas.png', 0, 0),
  ('image_permanent', 'inactive_kaltietis.png', 'png', 'Hinactive_kaltietisC', '/badge/inactive_kaltietis.png', 0, 0),
  ('image_permanent', 'inactive_merktiecigais.png', 'png', 'Hinactive_merktiecigaisC', '/badge/inactive_merktiecigais.png', 0, 0),
  ('image_permanent', 'inactive_piecenieks.png', 'png', 'Hinactive_piecenieksC', '/badge/inactive_piecenieks.png', 0, 0),
  ('image_permanent', 'inactive_professors.png', 'png', 'Hinactive_professorsC', '/badge/inactive_professors.png', 0, 0),
  ('image_permanent', 'inactive_puce.png', 'png', 'Hinactive_puceC', '/badge/inactive_puce.png', 0, 0),
  ('image_permanent', 'inactive_talredzigais.png', 'png', 'Hinactive_talredzigaisC', '/badge/inactive_talredzigais.png', 0, 0),
  ('image_permanent', 'inactive_udensvirs.png', 'png', 'Hinactive_udensvirsC', '/badge/inactive_udensvirs.png', 0, 0),
  ('image_permanent', 'inactive_zintkarais.png', 'png', 'Hinactive_zintkaraisC', '/badge/inactive_zintkarais.png', 0, 0),
  ('image_permanent', 'inactive_zoologs.png', 'png', 'Hinactive_zoologsC', '/badge/inactive_zoologs.png', 0, 0),

  ('image_permanent', 'dimond_icon.png', 'png', 'Hdimond_iconC', '/category/dimond_icon.png', 0, 0),
  ('image_permanent', 'leg_icon.png', 'png', 'Hleg_iconC', '/category/leg_icon.png', 0, 0),
  ('image_permanent', 'mount_icon.png', 'png', 'Hmount_iconC', '/category/mount_icon.png', 0, 0),
  ('image_permanent', 'rose_icon.png', 'png', 'Hrose_iconC', '/category/rose_icon.png', 0, 0),
  ('image_permanent', 'tower_icon.png', 'png', 'Htower_iconC', '/category/tower_icon.png', 0, 0),
  ('image_permanent', 'wave_icon.png', 'png', 'Hwave_iconC', '/category/wave_icon.png', 0, 0);